# Generated by Django 3.1.2 on 2020-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_commenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentType',
        ),
        migrations.AddField(
            model_name='comment',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
