# Generated by Django 3.1.2 on 2020-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201024_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_negative_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_positive_comments',
            field=models.IntegerField(default=0),
        ),
    ]
