# Generated by Django 3.1.2 on 2020-10-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201024_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('P', 'positive'), ('N', 'negative')], default='P', max_length=2),
        ),
    ]
