# Generated by Django 3.1.2 on 2020-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/pics03.jpg', upload_to='images'),
        ),
    ]
