# Generated by Django 3.1.2 on 2020-10-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201025_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/pics02.jpg', upload_to='images'),
        ),
    ]
